### ISSUE TITLE
wormhole-spy errored when Running EVM-EVM relayer

### ISSUE THREAD

**Issue by Alivers** [wormhole-foundation/relayer-engine#86] opened 2023-03-12 12:57 UTC
I'm trying run evm-evm relayer. The relayer started correctly, but it could't receive VAAs successful. So I checked the worm-spy and it logged the error as below:
`
44|spy  | 2023-03-12T12:51:27.498Z	ERROR	wormhole-spy	zap/options.go:212	finished streaming call with code Unknown	{"_privateLogEntry": true, "grpc.start_time": "2023-03-12T12:33:57Z", "system": "grpc", "span.kind": "server", "grpc.service": "spy.v1.SpyRPCService", "grpc.method": "SubscribeSignedVAA", "peer.address": "172.17.0.1:49858", "x-forwarded-for": [], "error": "context canceled", "grpc.code": "Unknown", "grpc.time_ms": 1050468.4}
`

Also, The spy had received the VAAs from wormhole guradiand.
`
44|spy     | 2023-03-12T12:19:04.719Z	INFO	wormhole-spy	spy/spy.go:512	Received signed VAA	{"vaa": "AQAAAAABAEc51s5Sl0/jE+2sfBXLOnBMc0tO/svbh+WuYTPUZsZIcwQJh9o3sL6qSoUOPIRQF+C5il94TvEd0oNPTdRDeYIAZA3DNwAAAAEABAAAAAAAAAAAAAAAAPFhZfEEbxs82zfaJeg1uYbmljE6AAAAAAAAAAEBSGVsbG8gcmVsYXllciBmcm9tIGV2bTE="}
`

Didn't know what happened in SPY process. Looking forward helping.

**Comment by solanoepalacio** [comment] 2023-03-12 18:41
Hi @Alivers 👋 
Thanks for opening this issue :). I'm new to wormhole, but I'm glad to try to help... Today I'm not at the office but I'll come back to you as soon as I can.
In the meantime... Can you tell me a little bit more about your relayer setup?

**Comment by Alivers** [comment] 2023-03-13 01:52
> 

Hi @solanoepalacio , I followed the steps described in xdapp-book to setup relayer: 
1. start EVM、Wormhole、SPY with command described in `https://github.com/wormhole-foundation/xdapp-book/blob/main/projects/wormhole-local-validator/package.json`
2. start my relayer with relayer-engine which followed Dummy Plugin example.

Here is my setup code:
```ts
async function main() {
  const xDappConfig: XDappConfig = JSON.parse(
    readFileSync("../../config/xdapp.config.json").toString()
  );
  const messengerABI = JSON.parse(
    readFileSync("../../aries-eth/out/Messenger.sol/Messenger.json").toString()
  ).abi;

  const registeredContracts = readdirSync("../../deployinfo")
    .filter(
      (fname) =>
        fname.split(".").length === 3 &&
        xDappConfig.networks[fname.split(".")[0]]
    )
    .map((fname) => {
      const file = JSON.parse(
        readFileSync(`../../deployinfo/${fname}`).toString()
      );
      const network = fname.split(".")[0];
      const chainId = xDappConfig.networks[network].wormholeChainId;
      return { chainId, contractAddress: file.address };
    });

  const relayerConfig = {
    envType: relayerEngine.EnvType.LOCALHOST,
    mode: relayerEngine.Mode.BOTH,
    storeType: "Redis",
    redis: {
      host: "127.0.0.1",
      port: 6379,
    },
    defaultWorkflowOptions: {
      maxRetries: 10,
    },
    wormholeRpc: "http://127.0.0.1:7071",
    supportedChains: Object.entries(xDappConfig.networks).map(
      ([networkName, network]) => {
        return {
          chainId: network.wormholeChainId,
          chainName: networkName,
          nodeUrl: network.rpc,
          bridgeAddress: network.bridgeAddress,
        };
      }
    ),
  };

  const plugin = new MessengerRelayerPlugin(
    relayerConfig,
    { registeredContracts, xDappConfig, messengerABI },
    relayerEngine.getLogger()
  );

  await relayerEngine.run({
    plugins: {
      [MessengerRelayerPlugin.pluginName]: (engineConfig, logger) => plugin,
    },
    configs: {
      executorEnv: {
        // @ts-ignore
        privateKeys: Object.fromEntries(
          Object.values(xDappConfig.networks).map((network) => {
            return [network.wormholeChainId, [network.privateKey]];
          })
        ),
      },
      listenerEnv: { spyServiceHost: "127.0.0.1:7073" },
      commonEnv: relayerConfig as relayerEngine.CommonEnv,
    },
    mode: relayerConfig.mode,
    envType: relayerConfig.envType,
  });
}
```

And the xdapp-config.json:
```json
{
  "networks": {
    "evm0": {
      "type": "evm",
      "wormholeChainId": 2,
      "rpc": "http://127.0.0.1:8545",
      "privateKey": "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d",
      "bridgeAddress": "0xC89Ce4735882C9F0f0FE26686c53074E09B0D550"
    },
    "evm1": {
      "type": "evm",
      "wormholeChainId": 4,
      "rpc": "http://127.0.0.1:8546",
      "privateKey": "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d",
      "bridgeAddress": "0xC89Ce4735882C9F0f0FE26686c53074E09B0D550"
    }
  },
  "wormhole": {
    "restAddress": "http://127.0.0.1:7071"
  }
}
```

**Comment by solanoepalacio** [comment] 2023-03-13 12:43
Hey @Alivers :wave: 
I'll dig into this issue today. I think I'll have some time to try to reproduce in the afternoon.
I'll come back to you asap

**Comment by Alivers** [comment] 2023-03-13 12:48
> Hey @Alivers 👋 I'll dig into this issue today. I think I'll have some time to try to reproduce in the afternoon. I'll come back to you asap

Also, here is the command I started the spy guardian. Both devnet and testnet not working with same error described above. Thanks for your work~
```bash
# Devnet
https://github.com/wormhole-foundation/xdapp-book/blob/cf471ffffe4ba2c456a485b8d54fa01188b23e8e/projects/wormhole-local-validator/package.json#L9

# testnet
#!/usr/bin/env bash

set -euo pipefail

# Check if Docker is running
docker ps > /dev/null #route error to console
echo "Docker is running"

# Start guardiand
npx pm2 delete spy 2> /dev/null || true
npx pm2 start 'docker run \
    --platform=linux/amd64 \
    -p 7073:7073 \
    --entrypoint /guardiand ghcr.io/wormhole-foundation/guardiand:latest spy \
    --nodeKey /node.key \
    --spyRPC "[::]:7073" \
    --network /wormhole/testnet/2/1 \
    --bootstrap /dns4/wormhole-testnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWAkB9ynDur1Jtoa97LBUp8RXdhzS5uHgAfdTquJbrbN7i' --name spy
```

**Comment by Alivers** [comment] 2023-03-13 13:09
> Is the VAA you posted the last one you got before the error? I see that you got the error (which seems to be a grpc stream error) about 32 minutes after you received the last VAA. In my short experience with the spy, I think it gets VAA way more often than that (many a second, I'd say...)
> 
> I've had the spy running the whole weekend with a quite similar configuration (pasted below). I just checked the logs for error, but didn't find this one
> 
> ```
>   spy:
>     image: ghcr.io/wormhole-foundation/guardiand:latest
>     container_name: spy
>     platform: linux/amd64
>     ports:
>       - '7073:7073'
>     entrypoint: /guardiand
>     command:
>       - spy
>       - --nodeKey
>       - /node.key
>       - --spyRPC
>       - "[::]:7073"
>       - --network
>       - /wormhole/testnet/2/1
>       - --bootstrap
>       - /dns4/wormhole-testnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWAkB9ynDur1Jtoa97LBUp8RXdhzS5uHgAfdTquJbrbN7i
> ```

The grpc stream error occurred when I run my relayer which based on relayer-engine. The SPY had received the VAAs when I run it. Things maybe not related with VAAs emitter.  I guess the problem should be Connection between SPY and Relayer, but don't know what happened.

**Comment by Alivers** [comment] 2023-03-13 13:26
Hi @solanoepalacio , I just got the error logged by my relayer:
```bash
2023-03-13 21:01:45.471|error|spyEventSource: spy service returned an error: Error: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/client.ts:597:51)
    at Object.onReceiveStatus (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/client.ts:580:30)
    at ServiceClientImpl.subscribeSignedVAA (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at /Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:50:42
    at step (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:33:23)
    at Object.next (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:14:53)
    at /Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:4:12)
    at subscribeSignedVAA (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:48:12)
    at runPluginSpyListener (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/github.com+wormhole-foundation+relayer-engine@cc0aad43787a87ecd9f0d9893d8ccf92901d7adb/node_modules/@wormhole-foundation/relayer-engine/relayer-engine/src/listener/spyEventSource.ts:84:40) {
  [stack]: 'Error: 1 CANCELLED: Call cancelled\n' +
    '    at callErrorFromStatus (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/call.ts:81:17)\n' +
    '    at Object.onReceiveStatus (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/client.ts:597:51)\n' +
    '    at Object.onReceiveStatus (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)\n' +
    '    at /Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:77:11)\n' +
    'for call at\n' +
    '    at ServiceClientImpl.makeServerStreamRequest (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/client.ts:580:30)\n' +
    '    at ServiceClientImpl.subscribeSignedVAA (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@grpc+grpc-js@1.8.12/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)\n' +
    '    at /Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:50:42\n' +
    '    at step (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:33:23)\n' +
    '    at Object.next (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:14:53)\n' +
    '    at /Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:8:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:4:12)\n' +
    '    at subscribeSignedVAA (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/@certusone+wormhole-spydk@0.0.1/node_modules/@certusone/wormhole-spydk/lib/cjs/index.js:48:12)\n' +
    '    at runPluginSpyListener (/Users/aliver/workspace/repo/aries/cross-aries/packages/relayer/node_modules/.pnpm/github.com+wormhole-foundation+relayer-engine@cc0aad43787a87ecd9f0d9893d8ccf92901d7adb/node_modules/@wormhole-foundation/relayer-engine/relayer-engine/src/listener/spyEventSource.ts:84:40)',
  [message]: '1 CANCELLED: Call cancelled',
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}  
2023-03-13 21:01:45.472|error|spyEventSource: spy service closed the connection!  
2023-03-13 21:01:51.404|info|spyEventSource: attempting to reconnect to the spy service  
2023-03-13 21:01:51.405|info|spyEventSource: MessengerRelayerPlugin subscribing to spy with raw filters: [{"chainId":2,"emitterAddress":"0x51b5da5A6eDB7D52A089359Ee40481280112a435"},{"chainId":5,"emitterAddress":"0x27E9Fab977Fdfda87779f0aB5fEA5B0d812A301c"}]  
2023-03-13 21:01:51.411|info|spyEventSource: connected to spy service, listening for transfer signed VAAs 
```

**Comment by solanoepalacio** [comment] 2023-03-13 16:22
So, a few things here:
1. If the problem is actually with the spy, this issue should be in the [wormhole repository](https://github.com/wormhole-foundation/wormhole), since the spy code is contained in that repository ([here](https://github.com/wormhole-foundation/wormhole/tree/main/node/cmd/spy) )

2. From the last set of logs you mentioned, it looks like the spy managed to re-connect after a few seconds. Let me expand on what you can expect from the relayer engine in this cases:
As you probably already know, The VAAs are produced continuosly and are ephimeral. So in the event of the spy disconnecting, you will be missing the VAAs emitted during the time the spy was down.
Relayer engine tries to solve this situation by fetching "missing VAAs". Essentially, the engine stores the last `sequence` (look at the [VAA body properties](https://book.wormhole.com/wormhole/4_vaa.html#body)) number it has received for a particular emitter chain and emitter address. If a VAA is received with a sequence that is greater than the last sequence received +1 (imagine `vaa_received_sequence > last_vaa_sequence_processed + 1`) then it will use the guardian API to fetch and process all VAAs that have been potentially missed

**Comment by Alivers** [comment] 2023-03-14 02:43
Thanks a lot @solanoepalacio. I checked the case again: The SPY received VAAs correctly, but it didn't return the VAA to my relayer. Maybe the filter incorrect or something else.

**Comment by Alivers** [comment] 2023-03-14 07:50
@solanoepalacio I had figured out it caused by my relayer configuration and startup order. Thanks for your time to help me.

**Comment by solanoepalacio** [comment] 2023-03-14 11:49
Glad to know to that! If possible, please describe the problem you ran into with the startup order, just in case someone else runs into it and finds this thread :)
I'll close this issue, we are here to help in case you have any other issue

**Closed by solanoepalacio** 2023-03-14 11:49 UTC

**Comment by Alivers** [comment] 2023-03-15 07:58
1. start spy guardian to watch the incoming VAAs
2. deploy contract on working blockchains
3. start relayer with chainId-emitter filters
4. emit VAA using contract function entry
